---
title: Life's events, like life, are nothing but a vapor.
authorbox: false
thumbnail: 'img/letter.png'
---

It appears and its sooner than later, nothing. Gone. A memory. A forgotten memory.

Many ways in which your time could be sub divided. Divisions over events that are soon
over after they start.

A holiday, a school session,a workout session,a morning shower, a job search work
,an X day work out challenge, a meeting with someone, a hard conversation,a meal
,a walk.

**** What to do about this finite nature:

Put in your all. Be present in every moment however mundane.
Because soon, it will be over.
And all that'll be left will be memories for what you did.
Or regrets about what you chose not to.

Take it as some form of encouragement, the finite nature of events.
Hard events, hard times are finite events too. A 10 day sprint of daily pushups
is as long as a night's sleep. You will get in and if you stick around, you are eventually out.
Don't forfeit a reward for how long it should take working towards it
if it be something you are interested in. How long is most often nothing.

*Live in the moment.*

Holidays? Enjoy the holidays. Put work off. Be very present.
There's time for everything thats not holiday related.

Hard conversations? Make the call. Trust me, it won't take years until whatever
the conversation entails is buried in memory.

Walks? Live in them. Enjoy every step. You don't get any back. I mean, you will never
remember a wasted walk but you might remember one you make memorable. So .. 

Meals? Don't rush through them. Enjoy every bite. What else is better to do
for a meal that will soon be a memory. 

Fear not the hard decisions. For most of your fears for what could be are irrational. And
you sure will enjoy what comes of facing the fears. Plus, most of the decisions only last
but minutes. Yet the rewards form lasting memories. Let those be memories, not regrets.

