---
title: "Last Week In Code E010: Reflection"
thumbnail: 'img/lwic.png'
date: 2026-06-25T09:21:15+03:00
draft: false
tags:
 - lwic
categories:
 - WeeklySeries
authorbox: false
---

/Last Week In Code E010 & Last Week in Cyprus/

I like how the series' name somehow saw this coming. I had no idea the same
acronym to mean what happened last week in my world of code I was going
to be able to use for refrence to my  'last week in Cyprus'.
Which, it now is. How  cool... !

So what was I doing this week? Well, like the week before the last one,
not much. A lot of packing and prep for my next destination. I should be writing
my next update from there. I'm guessing you too notice that's a very
long time not actively programming. And I notice too.
I am actually starting to feel the toll of it. But settling I hope should
some how fix that. 

Still as usual, that did not affect availability for what to share.
A lot has happened since [[/lwic/last-week-in-code-001][e001]].

*The good*

- I have been consistently posting every week for 10 weeks.

*The bad*

**** No fixed upload day.
- Some uploads come in on Thursday, some Wednesday, some Tuesday.
 

**** Wordiness and unnecessary detail
- I think I use a lot of words. The problem could be a lack of editing or
  a lack of time to edit. Which could be because I write every episode
  the very day when I upload it.

- Also, there's details added that I think are better left out or
  spoken about more abstractly. But that's for problem number next. /devolving/
  /structure/. 

**** Devolving structure.
- From writing for an audience to writing for self. Building on the previous
  point.  I interestingly had solid structure for episodes 001 and 002 but  as
  time past lost the plot. Started to ramble about all sorts of things.
  The series has since been devolving into some form of public stream of consciousness
  style diary. I think I will use the next 10 weeks to fix that. I like
  the benefits from writing for self. But I guess I can get the best of both
  worlds. The lack of pressure from the perception I have no audience and
  the structure from the perception I do. 

- Also, this reflection I am doing right now about the site's future and
  structure will have to move to somewhere else. Until 10 weeks since
  a reflection post. I have done some market research and found others
  have separate sections for this type of writing. And with good reasons.
  You have no business constantly following what challenges I am fixing. Only
  to see the results of it.
  
**** No contacts.
- Have you ever noticed I almost never add a contact me section at the end of
  my uploads?  

**** Summary
- I won't fix the all the issues in a single update but will keep this somewhere
  to slowly eat away at them with continuous improvement.  I hope to come
  back to this in e020 to check on progress.

*** More plans for the next 10 weeks.

It's so unreal a while back I wasn't sure if I was going to last past episode
two and now here I am.  So confidently planning the next 10 weeks. But anyways.

**** Podcasting.

Now this is going to be a somewhat ambitious undertaking. If I may share, I'd
like to have this evolve into something that sounds professional and technical
by around e040. I am still really behind on that schedule. But one step
at a time. 

I have no prior success podcasting but I guess I got to start somewhere.
The name will obviously be 'Last Week In Code'. The content and all other items
are still issues I am researching.


**** Building a community

I could have talked about building a community but I guess I can only
think about that if all goes well past e060 or so. That means doing some
publicity and having site structure that is worth the publicity.

But this seems so early to start thinking about community so I guess I
will just leave this tab open in my mind till I return to it.


*** Closing
Its been 10 weeks. I have no means to know who's been following since e001.
And that is by design. But if that's been you, thaanks. I am hoping to see
you around over the next 10 weeks also.




*Contact Me*

- [[https://bsky.app/profile/zymacs.bsky.social][BlueSky: zymacs]]
- [[https://t.me/@zymacs_1][Telegram: zymacs_1]]

