---
title: Last Week In Code E001
date: 2026-04-18
thumbnail: "img/lwic.png"
draft: true
tags:
  - lwic
categories:
  - WeeklySeries
---



I find I always have a whole lot to talk about at the end of every week.
And that most of it is from the tech space. I attend this Software Club
meeting every Thursday where I try to use some of that time to talk
about the latest developments with people who get it. We exchange
opinions on things we're building. You know how that is. So I was like,
how about I create something here that'll be an outlet for that? So I
did. Like many things I've started, I can't be sure this will last. But
I won't try to preemptively kill it either. May the Force be with it.
This week, I'm shipping the skeleton and letting the structure emerge
naturally as I pump in more episodes. My consumption is personal, so
what I include might skew toward my interests. Beware :)

** Updates From me
:PROPERTIES:
:CUSTOM_ID: updates-from-me
:END:
*** A new way to do project management
:PROPERTIES:
:CUSTOM_ID: a-new-way-to-do-project-management
:END:
So I've been moving my project management from scattered TODO lists to
[[https://github.com/features/issues][GitHub issues]]. And when I
finally got used to it, I wondered why I hadn't done that earlier. I
feel It's way better than what I was doing. Using a todo list that is.
The ease of centralization for issue tracking being one among other
reasons. Every time I think of an improvement, every time I notice a bug
while using my apps, I can always just add an issue to their
corresponding issue pages. And there's labeling too. That labeling
system is actually how I got my first
[[https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests][PR]].
If you are like how I was, not knowing much about this feature github
offers, here's an article that could get you started.
[[https://sifterapp.com/academy/overview/why/][click]]. So as part of a
larger app I had to create a
[[https://github.com/zymacs/Tomadoro][pomodoro app]]. I got the basics
down then moved the list of all I hadn't added to the project's issues
page. I labelled most of them 'good first issue'. And next day someone
sent in a PR asking to work on one of the issues. There's a lot of talk
online about how to get your pull requests accepted. But I'd never been
in the reviewer position before. Never felt that side of it.

*** Can't do it -- don't delegate it: Non-mainstream AI advice
:PROPERTIES:
:CUSTOM_ID: cant-do-it-dont-delegate-it-non-mainstream-ai-advice
:END:
So I beat myself up, the 1000th time, for choosing to use AI for
something I didn't understand. In one of my projects, a mostly CLI
driven app, I wanted to move from CLI to GUI. To build a django front
end. I was /feeling lazy/ and /wasn't ready to put in the time/ so I
gave the whole task to Grok. /Hours/ of prompting later, I ran the code
it generated and almost drowned in bugs. Bugs arising from concepts Grok
had used I that didn't understand. The lesson hit hard:

#+begin_quote
Don't assign AI tasks that you can't do yourself.
#+end_quote

I've seen myself go through the same process over and over but still
wonder why I keep coming back. A youtuber (Brodie Robertson) sums up my
point nicely
[[https://youtu.be/HRsdi7YJ8dI?si=q5xmIodwJF-GZ1FN&t=146][here]].

** In other news last week
:PROPERTIES:
:CUSTOM_ID: in-other-news-last-week
:END:
*AI & LLMs*

- [[https://www.youtube.com/watch?v=d3Qq-rkp_to][Claude Mythos is the OG
  -- Fireship]]
- [[https://www.youtube.com/watch?v=6szQxMGX5JI][The Prime's standup
  testing that claim]]

*Data Privacy & Cybersec*

- [[https://faq.whatsapp.com/337473702666585/?helpref=hc_fnav][Whatsapp
  rolling out end to end encrypted Ads -- Whatsapp]]

** A challenge for you
:PROPERTIES:
:CUSTOM_ID: a-challenge-for-you
:END:
/Can you tell how much of the above post was GPT?/ Until next week. Yes,
I should see you next week. That's the plan.. /May the force be with
you/
