---
title: 'The Cost for Not Documenting Solutions'
thumbnail: 'img/folder_icon.png'
date: 2026-04-24T20:08:02+03:00
draft: false
---

** The cost of not documenting your solutions

If you ever found yourself visiting the same stack overflow solution twice, thrice, four times. Maybe you should
start thinking about making some sort of documentation system for the errors you run into.

I have been doing so
for quite a while now and boy is it refreshing to run into an old error that sunk a load of my time for which I now have a recorded
the solution. Same could be said of those for which I did not take time to write something down. 
Those are very annoying. Its very annoying going through docs more than once to solve a problem you know
you solved in the past.

Its like, without docs,  all you have is dejavu about old occurences for the same problem:
/I saw this error, I fixed it, but i don't remember how i did../. 
You can't get yourself to remember what the solution was. If you somehow manage to get the primary source,
you still don't remember how you uderstood the solution it presented. Quadruple work.

Documentation can feel like a chore. But no one died from it. The one thats always gained from my notes is me.
I always like it when I know something would have taken a lot of time to do but, because of some past sacrifice to
take notes, it takes less than a fraction of standard time.

I have no standardized wiki yet. Org roam notes accessible with a /C-x C-f/ for now. But its something I am
definitely looking into. 


Hope you picked something from that that saves you some time in the future. 

